//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: lagu_sion.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Lagusion_LaguSionServiceClient, then call methods of this protocol to make API calls.
public protocol Lagusion_LaguSionServiceClientProtocol {
  func listAllSongs(_ request: SwiftProtobuf.Google_Protobuf_Empty, callOptions: CallOptions?) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Lagusion_ListSongResponse>
  func listSongs(_ request: Lagusion_ListSongsRequest, callOptions: CallOptions?) -> UnaryCall<Lagusion_ListSongsRequest, Lagusion_ListSongResponse>
}

public final class Lagusion_LaguSionServiceClient: GRPCClient, Lagusion_LaguSionServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the lagusion.LaguSionService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to ListAllSongs
  ///
  /// - Parameters:
  ///   - request: Request to send to ListAllSongs.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listAllSongs(_ request: SwiftProtobuf.Google_Protobuf_Empty, callOptions: CallOptions? = nil) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Lagusion_ListSongResponse> {
    return self.makeUnaryCall(path: "/lagusion.LaguSionService/ListAllSongs",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Unary call to ListSongs
  ///
  /// - Parameters:
  ///   - request: Request to send to ListSongs.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listSongs(_ request: Lagusion_ListSongsRequest, callOptions: CallOptions? = nil) -> UnaryCall<Lagusion_ListSongsRequest, Lagusion_ListSongResponse> {
    return self.makeUnaryCall(path: "/lagusion.LaguSionService/ListSongs",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}


// Provides conformance to `GRPCPayload` for request and response messages
extension SwiftProtobuf.Google_Protobuf_Empty: GRPCProtobufPayload {}
extension Lagusion_ListSongResponse: GRPCProtobufPayload {}
extension Lagusion_ListSongsRequest: GRPCProtobufPayload {}

