# load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")
# load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
#
# swift_library(
#     name = "LaguSionTestsSources",
#     srcs = glob(["**/*.swift"]),
#     deps = [
#         "//LaguSion:LaguSionSources",
#     ],
#     visibility = ["//visibility:private"],
# )
#
# ios_unit_test(
#     name = "LaguSionTests",
#     deps = [":LaguSionTestsSources"],
#     minimum_os_version = "13.0",
# )
