default_platform(:ios)

platform :ios do
  desc "Build iOS App"
  lane :build do
    match(type: "adhoc", readonly: true)
    build_app(
      scheme: "LaguSion",
      export_method: "ad-hoc",
      derived_data_path: "./d/",
      clean: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "LaguSion")
    upload_to_testflight
  end
end
