default_platform(:ios)

platform :ios do
  before_all do |lane|
    ENV['SLACK_CHANNEL'] = "#ios-build"
    ENV['APP_XCODEPROJ'] = "./LaguSion.xcodeproj"
    ENV['APP_TARGET'] = "LaguSion"
    ENV['BAZEL_BUILD_OUTPUT'] = "bazel-bin/LaguSion/LaguSion.ipa"

    if ENV['CI']
      setup_ci
    end
  end

  def current_version
    get_version_number(xcodeproj: ENV['APP_XCODEPROJ'], target:
    ENV['APP_TARGET'], configuration: "Debug")
  end

  def changelogs
    return changelog_from_git_commits(commits_count: 5, pretty: "\r\n• %s")
  end

  def build_appcenter_release_url(id)
    return "https://install.appcenter.ms/users/#{ENV['APPCENTER_OWNER_NAME']}/apps/#{ENV['APPCENTER_APP_NAME']}/distribution_groups/lagu%20sion%20testers/releases/#{id}"
  end

  def slack_team(message)
    slack(
      message: message,
      slack_url: ENV['SLACK_URL'],
      channel: ENV['SLACK_CHANNEL'],
      fail_on_error: false,
      default_payloads: []
    )
  end

  desc "Run Unit Tests"
  lane :unittest do
    run_tests(
      project: ENV['APP_XCODEPROJ'],
      scheme: "LaguSion",
      configuration: "Debug",
      derived_data_path: "DerivedDataUnitTest",
      clean: false,
      slack_url: ENV['SLACK_URL'],
      slack_channel: ENV['SLACK_CHANNEL'],
      slack_message: "Unit Test Result for #{ENV['GITHUB_REF']} in workflow #{ENV['GITHUB_WORKFLOW']}",
      slack_only_on_failure: true,
      output_types: "html",
      code_coverage: true,
      reinstall_app: true
    )
  end

  desc "Build iOS App"
  lane :build do
    unittest

    increment_build_number_in_plist(
      build_number: current_version + "-" + ENV['GITHUB_REF'] + "-" + (ENV['GITHUB_WORKFLOW'] || "Local") + "-" + (ENV['GITHUB_RUN_NUMBER'] || "0"),
      xcodeproj: ENV['APP_XCODEPROJ']
    )

    disable_automatic_code_signing(path: ENV['APP_XCODEPROJ'])

    match(
      type: "adhoc", 
      readonly: true,
    )

    build_app(
      scheme: "LaguSion",
      export_method: "ad-hoc",
      derived_data_path: "./DerivedData/"
    )
    ENV['IPA_OUTPUT_PATH'] = lane_context[SharedValues::IPA_OUTPUT_PATH]
    appcenter
  end

  desc "Upload to AppCenter"
  lane :appcenter do
    appcenter_upload(
      api_token: ENV['APPCENTER_API_TOKEN'],
      owner_name: ENV['APPCENTER_OWNER_NAME'],
      owner_type: "user",
      app_name: ENV['APPCENTER_APP_NAME'],
      app_os: "iOS",
      destinations: "*",
      file: (ENV['IPA_OUTPUT_PATH'] || ENV['BAZEL_BUILD_OUTPUT']),
      release_notes: changelogs
    )

    version = appcenter_fetch_version_number(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME"]
    )

    slack_team("Workflow #{ENV['GITHUB_WORKFLOW']} successful. #{build_appcenter_release_url(version["id"])}")
  end

  desc "Capture screenshots"
  lane :screenshots do
    capture_screenshots
    frame_screenshots
  end
end
