name: bazel-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 11.5
      run: sudo xcode-select -s /Applications/Xcode_11.5.app
    - name: Cache Gems
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-bundle-install
      with:
        path: ./vendor/
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Install Gems
      run: |
        bundle install --deployment
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup CI Environment
      run:
        bundle exec fastlane run setup_ci
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Cache Tests
      uses: actions/cache@v1
      env:
        cache-name: cache-bazel-test
      with:
        path: /private/var/tmp/_bazel_runner
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Match Development Provisioning Profile
      run: |
        bundle exec fastlane match development --readonly --output_path=./LaguSion/provision/ --keychain_name=fastlane_tmp_keychain
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Run SongTests
      run: bazel test //SongTests
    - name: Run FavoritesTests
      run: bazel test //FavoritesTests
    - name: Run MainTests
      run: bazel test //MainTests
    - name: Run iOS Application Tests
      run: bazel test //LaguSionTests
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: test
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 11.5
      run: sudo xcode-select -s /Applications/Xcode_11.5.app
    - name: Cache Gems
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-bundle-install
      with:
        path: ./vendor/
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Install Gems
      run: |
        bundle install --deployment
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Setup CI Environment
      run:
        bundle exec fastlane run setup_ci
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Cache Build
      uses: actions/cache@v1
      env:
        cache-name: cache-bazel-build
      with:
        path: /private/var/tmp/_bazel_runner
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Match Ad Hoc Provisioning Profile
      run: |
        bundle exec fastlane match adhoc --readonly --output_path=./LaguSion/provision/ --keychain_name=fastlane_tmp_keychain
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Build iOS Application
      run: |
        bazel build //LaguSion --config=device_adhoc
    - name: Upload artifacts to AppCenter
      run: |
        bundle exec fastlane appcenter
