name: Bazel-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Cache bazel build artifacts
      uses: actions/cache@v1
      env:
        cache-name: cache-bazel-lagu-sion-ios
      with:
        path: /private/var/tmp/_bazel_runner
        key: ${{ runner.os }}-bazel-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-bazel-build-${{ env.cache-name }}
          ${{ runner.os }}-bazel-build-
          ${{ runner.os }}-bazel-
    - name: Run bundle install
      run: |
        bundle install --deployment
    - name: Run fastlane match
      run: |
        bundle exec fastlane match --readonly --output_path=./provision/
      with:
        token: ${{ secrets.PAT }}
    - name: Run bazel build
      run: |
        bazel build //LaguSion
