name: Fastlane-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle install
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-bundle-install
      with:
        path: ./vendor/
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Run bundle install
      run: |
        bundle install --deployment
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Cache fastlane build artifacts
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-lagu-sion-ios
      with:
        path: ./d/
        key: ${{ runner.os }}-fastlane-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-fastlane-build-${{ env.cache-name }}
          ${{ runner.os }}-fastlane-build-
          ${{ runner.os }}-fastlane-
    - name: Run fastlane build
      run: bundle exec fastlane build
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: pwd and ls
      run: |
        pwd
        ls
