name: Fastlane-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 11.4.1
      run: sudo xcode-select -s /Applications/Xcode_11.4.1.app
    - name: Cache bundle install
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-bundle-install
      with:
        path: ./vendor/
        key: ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Run bundle install
      run: |
        bundle install --deployment
   - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Cache fastlane build artifacts
      uses: actions/cache@v1
      env:
        cache-name: cache-fastlane-build
      with:
        path: ./d/
        key: ${{ runner.os }}-fastlane-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-lagu-sion-ios-${{ env.cache-name }}
    - name: Run fastlane build
      run: bundle exec fastlane build
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Get branch name and commit sha
      id: vars
      run: |
        echo ::set-output name=git_branch::${GITHUB_REF#refs/*/}
        echo ::set-output name=git_hash=$(git rev-parse --short "$GITHUB_SHA")
    - uses: actions/upload-artifact@v2
      with:
        name: LaguSion-${{ steps.vars.outputs.git_branch }}-${{ steps.vars.outputs.git_hash }}
        path: LaguSion.ipa
    - name: pwd and ls
      run: |
        pwd
        ls 
